import Login from "@/components/Login/Login";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "UM - Login",
  description: "Generated by create next app",
};

const LoginPage = () => {
  return <Login />;
};

export default LoginPage;
